In [2]:
import pandas as pd

df = pd.read_csv("SimpsonsData_es.csv")

In [14]:
df

,Season,Title,Airdate,Rating,Vote_count,Description
0,1,Los Simpson asándose sobre un fuego abierto,17 dic. 1989,8.2,5633.0,La familia se ve obligada a gastar todos sus a...
1,1,"Bart, el genio",14 ene. 1990,7.7,3580.0,Bart termina en una escuela para niños superdo...
2,1,La odisea de Homer,21 ene. 1990,7.4,3145.0,"Después de perder su trabajo, Homer contempla ..."
3,1,No hay desgracia como el hogar,28 ene. 1990,7.7,3087.0,Después de que el resto de la familia lo averg...
4,1,"Bart, el general",4 feb. 1990,8.0,3130.0,Después de que Nelson Muntz lo golpea una vez ...
...,...,...,...,...,...,...
679,31,Sacerdotes en guerra,26 abr. 2020,6.0,332.0,El reverendo Alegría investiga el misterioso p...
680,31,"Sacerdotes en guerra, parte 2",3 may. 2020,5.7,296.0,"En Michigan, el reverendo Alegría descubre la ..."
681,31,Las odiosas niñas de ocho años,10 may. 2020,6.7,277.0,Lisa se une a un grupo de chicas ricas cuando ...
682,31,El camino del perro,17 may. 2020,7.4,288.0,Los Simpson exploran el trágico pasado de Ayud...
683,32,Episodio n.º 32.1,27 sep. 2020,NaN,NaN,¿Sabes de qué se trata? Sé la primera persona ...

In [5]:
df.tail()

,Season,Title,Airdate,Rating,Vote_count,Description
679,31,Sacerdotes en guerra,26 abr. 2020,6.0,332.0,El reverendo Alegría investiga el misterioso p...
680,31,"Sacerdotes en guerra, parte 2",3 may. 2020,5.7,296.0,"En Michigan, el reverendo Alegría descubre la ..."
681,31,Las odiosas niñas de ocho años,10 may. 2020,6.7,277.0,Lisa se une a un grupo de chicas ricas cuando ...
682,31,El camino del perro,17 may. 2020,7.4,288.0,Los Simpson exploran el trágico pasado de Ayud...
683,32,Episodio n.º 32.1,27 sep. 2020,NaN,NaN,¿Sabes de qué se trata? Sé la primera persona ...

In [13]:
df.sort_values("Rating", ascending=False)[["Season", "Title"]]

     Season                                        Title
154       8                       Solo se muda dos veces
175       8                          El enemigo de Homer
127       6  ¿Quién le disparó al señor Burns? Parte uno
82        5                            El cabo del miedo
108       6                       La casita del horror V
..      ...                                          ...
658      30                                  D'oh Canadá
188       9                       Todo canto, todo baile
655      30                      Bart contra Tomy y Daly
507      23                          Lisa se vuelve Gaga
683      32                            Episodio n.º 32.1

[684 rows x 2 columns]

In [17]:
promedio = df["Rating"].mean()
promedio

np.float64(7.205563689604685)

In [22]:
df2 = df["Rating"].value_counts()

In [25]:
df2

Rating
7.1    42
7.0    40
6.8    39
6.9    36
6.7    36
6.6    35
6.5    33
8.2    28
7.3    26
7.2    25
6.3    24
7.8    22
6.2    22
7.7    21
8.1    21
6.4    21
8.3    19
7.6    18
8.6    16
8.0    15
7.9    15
7.5    14
6.1    14
8.4    12
8.5    10
5.9    10
7.4     8
8.8     7
8.7     7
8.9     6
6.0     6
9.0     5
5.6     5
9.1     4
5.7     4
9.2     3
5.8     3
5.2     3
9.3     2
5.5     2
5.0     1
5.4     1
3.9     1
4.5     1
Name: count, dtype: int64